### ISSUE TITLE
Initial Meeting

### ISSUE THREAD

**Issue by RichardLitt** [papers-we-love/boston#1]
Things we need!
- [x] Find a place to meet.
- [x] Choose a date
- [x] Pick an initial paper // person to talk about it.

Advertising is also necessary. See issue #2.

**Comment by RichardLitt** [comment]
Ok, so, not much movement here. Perhaps we should start with a date, and go from there? December 10th?  cc @eglassman 

I don't have anywhere to present, yet. Worse comes to worst we can meet in a restaurant/bar.

**Comment by eglassman** [comment]
Ack. I dropped the ball! I have contacted Danger!Awesome about using their space. I suggest any night between Sunday Dec. 13th and Thursday Dec. 17th.

**Comment by RichardLitt** [comment]
No worries, I have too! Awesome. Let's aim for Tuesday night, the 15th? Seems a good date.

**Comment by eglassman** [comment]
Great!

**Comment by RichardLitt** [comment]
@eglassman ahhh. Any news on Danger!Awesome's space? I was able to find another place we can do it, at Bocoup's offices. It's where they were held before the organizer @ashleygwilliams moved away.

**Comment by RichardLitt** [comment]
Next week may be cutting it pretty close, at this point, though! My hope-for-the-best may not have worked.

**Comment by abenik** [comment]
working on the meet-up group.  I just sent you an invite.  Join it and then i can make you a co-organizer.

**Comment by RichardLitt** [comment]
Sweet. Joined. 

Now we just need a speaker. I'll post on Twitter, I guess?

**Comment by abenik** [comment]
yah.  I'm striking out given short-ish notice.  A few more feelers still out.  We may have to move from the 3rd but definitely but out a feeler on twitter and see if anyone wants to volunteer.

**Comment by abenik** [comment]
also.  if you want to make the Meet-up page a little prettier, feel free. I know the current state might offend your UX sensibilities :-)

**Comment by tel** [comment]
Oh! Nice! This is getting rolling again?

**Comment by tel** [comment]
I don't know if I'll have time to do a talk again (my last one was _way_ too long and involved, I can do better, but I'm still swamped right this moment) but I'd love to keep in touch and help out a bit.

**Comment by abenik** [comment]
This page is still a work in progress but join the group and you'll get updates.   Also if you know anyone who might be interested to give a talk feel free to send them this direction. 
http://www.meetup.com/Papers-We-Love-Boston-Cambridge/

**Comment by tel** [comment]
Joined!

**Comment by RichardLitt** [comment]
How does March 21, 22, or 23rd look for everyone? I'll give a talk. Seems the easiest way, as no one else is likely to come forward.

**Comment by tel** [comment]
That sounds good to me. What would the location be?

**Comment by abenik** [comment]
3/22 or 3/23 work for me and we can host at our office in Seaport.  Also locked in a speaker for 4/21 so we have a little momentum.

**Comment by tel** [comment]
:boom:

**Comment by abenik** [comment]
@RichardLitt 23rd at our office works.  let me know what your planned topic/paper is and I'll update the meetup for the March and April Mtgs.

**Comment by RichardLitt** [comment]
@abenik Sounds good. Working on finding a good paper, will update you in next few days. I'm on it.

**Comment by abenik** [comment]
how do people feel about saying the meet-up opens at 6 for mingling and eating and the talk starts around 6.30?

**Comment by RichardLitt** [comment]
Sounds good to me!

Bio: Richard Littauer is a computer scientist and developer who lives in Cambridge. He works for IPFS (ipfs.io), building a distributed, permanent internet, and reads papers and books in his constantly dwindling spare time. He's most well known for writing the dictionary for the Na'vi language, and for getting paid to review websites while drunk at theuserisdrunk.com.
Paper: "The Moral Character of Cryptographic Work" by Phillip Rogaway of UC Davis. http://web.cs.ucdavis.edu/~rogaway/papers/moral-fn.pdf

**Comment by abenik** [comment]
Meetup scheduled and public. Spread the word, this is happening!

**Comment by abenik** [comment]
April meet-up getting announced today.  Peter Bailis on Streaming queries over streaming data.  4/21.

**Comment by RichardLitt** [comment]
This was done! We should announce future events in new issues.
