### ISSUE TITLE
Twitter Account

### ISSUE THREAD

**Issue by RichardLitt** [papers-we-love/boston#3]
I've asked the guy who has the twitter account for the key. Hopefully, I'll be able to get access to it.

**Comment by RichardLitt** [comment]
I now have access to the twitter account, and I have the password for it. If anyone wants to help me tweet, let me know!

**Comment by RichardLitt** [comment]
I also have access to the YouTube // Google+ page, which means we can livestream and save presentations as needed.

**Comment by abenik** [comment]
Awesome.  The link on the twitter page hits the old, no defunct meet-up page.  Can you update it? 
http://www.meetup.com/Papers-We-Love-Boston-Cambridge/

**Comment by RichardLitt** [comment]
Updated!
